[features]
seeds = false
skip-lint = false

[programs.devnet]
ocf_presale = "REPLACE_WITH_YOUR_DEPLOYED_PROGRAM_ID"

[programs.mainnet]
ocf_presale = "REPLACE_WITH_YOUR_DEPLOYED_PROGRAM_ID"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts" 